#### Building Docker Image ####
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/nodeapp/myapp:$SHORT_SHA', '.' ]

#### Pushing Docker Image ####
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push us-docker.pkg.dev/$PROJECT_ID/nodeapp/myapp:$SHORT_SHA

# This step generates the new manifest
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  # secretEnv: ['GIT_ACCESS_TOKEN']
  args:
  - '-c'
  - |
    git clone https://github.com/ApurvShingne/mynodeapp.git -b main
    echo "Updating image tag version ..."
    cd mynodeapp
    sed "s/GOOGLE_CLOUD_PROJECT/$PROJECT_ID/g" deployment.yaml | \
    sed "s/COMMIT_SHA/${SHORT_SHA}/g" > deployment.yaml
    git remote add origin https://github.com/ApurvShingne/mynodeapp.git
    echo "Pushing changes to k8s manifest repo ..."
    git add -A
    git commit -m "[Cloud Builder] Updated image tag us-docker.pkg.dev/$PROJECT_ID/nodeapp/myapp:$SHORT_SHA from commit ${COMMIT_SHA}"
    git push origin main
    
# availableSecrets:
#   secretManager:
#   - versionName: projects/$PROJECT_NUMBER/secrets/github-access-token/versions/latest
#     env: 'GIT_ACCESS_TOKEN'

# # options:
# #   logging: CLOUD_LOGGING_ONLY